baseURL = "http://beamkenya.com/"
languageCode = "en-gb"
title = "Beam Kenya"
theme = "parsa-hugo"

[params]
layout = "2"
author_image = "images/banner-img.png"
bio = "We are a group of Kenyans interested in languages that run on the erlang beam, we organise and coordinate pair and mob programming sessions, webinars and build libraries for the community"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# social site

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/elixirkenya"

[[params.social]]
icon = "ti-telegram"
URL = "https://t.me/elixirkenya"


[[params.social]]
icon = "ti-github"
URL = "https://github.com/elixirkenya/"
